// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.BPU2March11.subsystems;

import org.usfirst.frc3566.BPU2March11.RobotMap;
import org.usfirst.frc3566.BPU2March11.commands.*;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class BPU2System extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController rubberBandPullerBarPWM8 = RobotMap.bPU2SystemRubberBandPullerBarPWM8;
    private final SpeedController bPU2RiserMotorRightPWM7 = RobotMap.bPU2SystemBPU2RiserMotorRightPWM7;
    private final SpeedController bPU2RiserMotorLeftPWM6 = RobotMap.bPU2SystemBPU2RiserMotorLeftPWM6;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
         setDefaultCommand(new DriveBPUWithJoysticks());
    }
    
    
    public void riserUp(){
    	
    	bPU2RiserMotorRightPWM7.set(RobotMap.BPU2_RISER_MOTOR_SPEED * -1.0);
    	bPU2RiserMotorLeftPWM6.set(RobotMap.BPU2_RISER_MOTOR_SPEED * -1.0);
    }
    
    
    public void riserDown(){
    	
    	bPU2RiserMotorRightPWM7.set(RobotMap.BPU2_RISER_MOTOR_SPEED );
    	bPU2RiserMotorLeftPWM6.set(RobotMap.BPU2_RISER_MOTOR_SPEED );
    }
    
    public void riserStop(){
    	bPU2RiserMotorRightPWM7.set(0.0);
    	bPU2RiserMotorLeftPWM6.set(0.0 );
    }
    
    public void runRubberBandBallGrabForward(){
    	rubberBandPullerBarPWM8.set(RobotMap.BPU2_RUBBER_BAND_BALL_PULLER_SPEED);
    }
    
    public void runRubberBandBallGrabBackwards(){
    	rubberBandPullerBarPWM8.set(RobotMap.BPU2_RUBBER_BAND_BALL_PULLER_SPEED * -1.0);
    }
    
    public void runRubberBandBallGrabStop(){
    	rubberBandPullerBarPWM8.set(0.0);
    }
}

