// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.chasis2016;


import org.usfirst.frc3566.chasis2016.commands.*;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
/**
 * test reverse button
 * make it so robot recenters based on z axis
 * 
 * driving practice
 * make it so driver knows which direction wheels either camera or smart dashboard
 * make a better autonomous
 * 
 * 
 * 
 *
 
 * 
 * Don't blow up the robot
 * 
 * 
 */

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Joystick joystick1;
    public Joystick xBoxController; 
    public Joystick logitechController; 
    public JoystickButton frontWindowMotorPositive;
    public JoystickButton frontWindowMotorNegative;
    public JoystickButton backWindowMotorPositive;
    public JoystickButton backWindowMotorNegative;
    public JoystickButton bothWindowMotorPositive;
    public JoystickButton bothWindowMotorNegative;
    public JoystickButton BPUliftUp;
    public JoystickButton BPUliftDown;
    public JoystickButton reCenterFront;
    public JoystickButton reCenterBack;
    public JoystickButton creepDrive;
    public JoystickButton xBoxRecenterFront;
    public JoystickButton xBoxRecenterBack;
    public JoystickButton bpuGoToMin;
    public JoystickButton bpuGoToMiddle;
    public JoystickButton bpuGoToMax;
    public JoystickButton solenoid; 
    
    //catapult
    public JoystickButton b1CockCatapult;
    public JoystickButton b2TriggerCatapultFIRE;
    public JoystickButton b3ResetTriggers;
    public JoystickButton b5MoveCatHorizontalLeft;
    public JoystickButton b6MoveCatHorizontalRight;
    public JoystickButton b7MoveAimerForwards;
    public JoystickButton b8MoveAimerBackwards;
    public JoystickButton b11BIGWinchDogGearDisengage;
    public JoystickButton b12BigWinchDogGearEngage;
    public JoystickButton b9CatapultWithJoysticks;
    public Joystick logitechXBoxType;
    public JoystickButton reverseButton; 
    
    
    //catapult end
    
    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	
        joystick1 = new Joystick(0);
        xBoxController = new Joystick(1); 
    	logitechXBoxType = new Joystick(2); 
    	reverseButton = new JoystickButton(joystick1, 1000000);//////**********!!!!!!
    	reverseButton.whenPressed(new reverseDriving());

    	//Right now we have three joysticks!! which is not good
    	//we'd have to combine the second joystick and the third one.
    	//if you see this remind me to change it
     
        solenoid = new JoystickButton(xBoxController, 8 );// 8 = start button
        
        frontWindowMotorPositive = new JoystickButton(joystick1, 8);
        frontWindowMotorPositive.whileHeld(new positiveWindowTurning(1));
        frontWindowMotorNegative = new JoystickButton(joystick1, 7);
        frontWindowMotorNegative.whileHeld(new negativeWindowTurning(1));
        
        backWindowMotorPositive = new JoystickButton(joystick1, 9);
        backWindowMotorPositive.whileHeld(new positiveWindowTurning(-1));
        // turns right, decreases potentiometer minimum 2.3 
        
        backWindowMotorNegative = new JoystickButton(joystick1, 10);
        backWindowMotorNegative.whileHeld(new negativeWindowTurning(-1));
        // turns left increases potentiometer 5.8
        
        bothWindowMotorPositive = new JoystickButton(joystick1, 11);
        bothWindowMotorPositive.whileHeld(new positiveWindowTurning(1));
        bothWindowMotorPositive.whileHeld(new positiveWindowTurning(-1));
        bothWindowMotorNegative = new JoystickButton(joystick1, 12);
        bothWindowMotorNegative.whileHeld(new negativeWindowTurning(1));
        bothWindowMotorNegative.whileHeld(new negativeWindowTurning(-1));
        
        BPUliftUp = new JoystickButton(xBoxController, 1);
        BPUliftUp.whileHeld(new BPUdown());
        BPUliftDown = new JoystickButton(xBoxController, 2);
        BPUliftDown.whileHeld(new BPUup());
        
        reCenterFront = new JoystickButton(joystick1, 5);
        reCenterFront.whenPressed(new recenterFrontWheel());
        
        reCenterBack = new JoystickButton(joystick1, 6);
        reCenterBack.whenPressed(new recenterBackWheels());
        

        //reCenterFront = new JoystickButton(xBoxController, 3);
       // reCenterFront.whenPressed(new recenterFrontWheel());
        
        //reCenterBack = new JoystickButton(xBoxController, 4);
       // reCenterBack.whenPressed(new recenterBackWheels());
        
       //catapult

        
        b12BigWinchDogGearEngage = new JoystickButton(logitechXBoxType, 12);
        b12BigWinchDogGearEngage.whenPressed(new BigMotorSetDogForPulling());
        b11BIGWinchDogGearDisengage = new JoystickButton(logitechXBoxType, 11);
        b11BIGWinchDogGearDisengage.whenPressed(new BigMotorSetDogToFIRE());
        b8MoveAimerBackwards = new JoystickButton(logitechXBoxType, 8);
        b8MoveAimerBackwards.whileHeld(new MoveCatAngleAimerBackwards());
        b7MoveAimerForwards = new JoystickButton(logitechXBoxType, 7);
        b7MoveAimerForwards.whileHeld(new MoveCatAngleAimerForward());
        b6MoveCatHorizontalRight = new JoystickButton(logitechXBoxType, 6);
        b6MoveCatHorizontalRight.whileHeld(new MoveRightHorizontal());
        b5MoveCatHorizontalLeft = new JoystickButton(logitechXBoxType, 5);
        b5MoveCatHorizontalLeft.whileHeld(new MoveLeftHorizontal());
        b3ResetTriggers = new JoystickButton(logitechXBoxType, 3);
        b3ResetTriggers.whenPressed(new ResetTriggers());
        b2TriggerCatapultFIRE = new JoystickButton(logitechXBoxType, 2);
        b2TriggerCatapultFIRE.whenPressed(new TriggerTheCatapult());
        b1CockCatapult = new JoystickButton(logitechXBoxType, 1);
        b1CockCatapult.whenPressed(new CockTheCatapult()); 
        
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("CatapultWithJoySticks", new CatapultWithJoySticks());
        SmartDashboard.putData("CockTheCatapult", new CockTheCatapult());
        SmartDashboard.putData("MoveLeftHorizontal", new MoveLeftHorizontal());
        SmartDashboard.putData("MoveRightHorizontal", new MoveRightHorizontal());
        SmartDashboard.putData("ResetTriggers", new ResetTriggers());
        SmartDashboard.putData("BigMotorSetDogForPulling", new BigMotorSetDogForPulling());
        SmartDashboard.putData("BigMotorSetDogToFIRE", new BigMotorSetDogToFIRE());
        SmartDashboard.putData("RunCatWinchForward", new RunCatWinchForward());
        SmartDashboard.putData("RunCatWinchBackwards", new RunCatWinchBackwards());
        SmartDashboard.putData("MoveCatAngleAimerForward", new MoveCatAngleAimerForward());
        SmartDashboard.putData("MoveCatAngleAimerBackwards", new MoveCatAngleAimerBackwards());
        SmartDashboard.putData("TriggerTheCatapult", new TriggerTheCatapult());
        SmartDashboard.putData("RulerWinchEndGameJoySticks", new RulerWinchEndGameJoySticks());
        //SmartDashboard.putData("Solenoit", new testSolenoid());
        //catapult end
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getLogitechXBoxType() {
        return logitechXBoxType;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    
    public double getLogitechYAxis(){
    	return logitechXBoxType.getY();
    	
    }
    
    public double getLogitechRawAxis3(){
    	
    	return logitechXBoxType.getRawAxis(3);
    }
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick1() {
        return joystick1;
    }
    
    public double getX() {
    	return joystick1.getRawAxis(0);
    }
    
    public double getY() {
    	
    	return joystick1.getRawAxis(1);
    }
    
    public double getZ() {
    return joystick1.getRawAxis(2);
    }
    public double getxBoxY(){
    	return xBoxController.getRawAxis(1);
    }
    /*public double getLogitech3Axis() {
    	return logitechXBoxType.getRawAxis(3);
    }*/
    
    public double getLogitechRawAxis1(){
    	
    	return logitechXBoxType.getRawAxis(1);
    }
    
    public double getWinchAxis() {
    	return xBoxController.getRawAxis(5);
    }
    }
//}

