// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.chasis2016.commands;

import edu.wpi.first.wpilibj.command.Command;


import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3566.chasis2016.Robot;
import org.usfirst.frc3566.chasis2016.Robot.*;
import org.usfirst.frc3566.chasis2016.RobotMap;
import org.usfirst.frc3566.chasis2016.RobotMap.*;

/**
 *
 */
public class GimbalRightHorizontal extends Command {

	private double timeout=RobotMap.GIMBAL_TIMEOUT;
	private boolean stopornot = false; 
    public GimbalRightHorizontal() {

 
    }
    public GimbalRightHorizontal(double timeOut){
    	timeout=timeOut; 
    	Robot.horizontalGimbalTurning.stopHorizontalGimbal();
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    	this.setTimeout(timeout);
    	Robot.horizontalGimbalTurning.moveHorizontalRight();
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	SmartDashboard.putNumber("potentiometer", RobotMap.sensorAnalogPotentiometer1.get());
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return this.isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.horizontalGimbalTurning.stopHorizontalGimbal();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.horizontalGimbalTurning.stopHorizontalGimbal();
    }
}
