// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.LaserSystem.subsystems;

import org.usfirst.frc3566.LaserSystem.RobotMap;
import org.usfirst.frc3566.LaserSystem.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class LaserGimbal extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
   // CANJaguar cAN2HRotation = RobotMap.laserGimbalCAN2HRotation;
   // CANJaguar cAN3VRotation = RobotMap.laserGimbalCAN3VRotation;
    Servo triggerServoPWM0 = RobotMap.laserGimbalTriggerServoPWM0;
    Servo reloadCatchPWM1 = RobotMap.laserGimbalReloadCatchPWM1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANTalon cAN2HRotation = RobotMap.laserGimbalCAN2HRotation;
    CANTalon cAN3VRotation = RobotMap.laserGimbalCAN3VRotation;

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        setDefaultCommand(new LaserJoysticks());
    }
    
    public void horizontalTurnLeft(){
    	
    	System.out.println("Hi from horizontalTurn Left");
    	
    	
    }
    
    public void horizontalTurnRight(){
    	System.out.println("Hi from horizontalTurn Right");
    	
    }
    
  public void verticalUp(){
    	
    	System.out.println("Hi from vertical Up");
    		
    }
  
  
  public void verticalDown(){
	  System.out.println("Hi from vertical Down");
  }
}

