// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.LaserSystem;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
   // public static CANJaguar laserGimbalCAN2HRotation;
   // public static CANJaguar laserGimbalCAN3VRotation;
    public static Servo laserGimbalTriggerServoPWM0;
    public static Servo laserGimbalReloadCatchPWM1;
    
    
    public static CANTalon laserGimbalCAN2HRotation;
    public static CANTalon laserGimbalCAN3VRotation;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        laserGimbalCAN2HRotation = new CANTalon(2);
        
        
        laserGimbalCAN3VRotation = new CANTalon(3);
        
        
        laserGimbalTriggerServoPWM0 = new Servo(0);
        LiveWindow.addActuator("LaserGimbal", "TriggerServoPWM0", laserGimbalTriggerServoPWM0);
        
        laserGimbalReloadCatchPWM1 = new Servo(1);
        LiveWindow.addActuator("LaserGimbal", "ReloadCatchPWM1", laserGimbalReloadCatchPWM1);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
