// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.BPU2March11;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController bPU2SystemRubberBandPullerBarPWM8;
    public static SpeedController bPU2SystemBPU2RiserMotorRightPWM7;
    public static SpeedController bPU2SystemBPU2RiserMotorLeftPWM6;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static final double BPU2_RISER_MOTOR_SPEED = 0.5;
    public static final double BPU2_RUBBER_BAND_BALL_PULLER_SPEED = 0.5;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        bPU2SystemRubberBandPullerBarPWM8 = new Talon(8);
        LiveWindow.addActuator("BPU2System", "RubberBandPullerBarPWM8", (Talon) bPU2SystemRubberBandPullerBarPWM8);
        
        bPU2SystemBPU2RiserMotorRightPWM7 = new Talon(7);
        LiveWindow.addActuator("BPU2System", "BPU2RiserMotorRightPWM7", (Talon) bPU2SystemBPU2RiserMotorRightPWM7);
        
        bPU2SystemBPU2RiserMotorLeftPWM6 = new Talon(6);
        LiveWindow.addActuator("BPU2System", "BPU2RiserMotorLeftPWM6", (Talon) bPU2SystemBPU2RiserMotorLeftPWM6);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
