

package org.usfirst.frc3566.VisionGimbalTestCCRJan19.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3566.VisionGimbalTestCCRJan19.Robot;
import org.usfirst.frc3566.VisionGimbalTestCCRJan19.RobotMap;

/**
*
*/
public class FireLaserGun extends Command {

 // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

 // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

 // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
 public FireLaserGun() {

 // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

 // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
 }

 // Called just before this Command runs the first time
 protected void initialize() {
 	
 	this.setTimeout(0.5);
 	Robot.horizontalGimbalTurning.fireLaser();
 }

 // Called repeatedly when this Command is scheduled to run
 protected void execute() {
 }

 // Make this return true when this Command no longer needs to run execute()
 protected boolean isFinished() {
     return false;
 }

 // Called once after isFinished returns true
 protected void end() {
	 Robot.horizontalGimbalTurning.resetLaser();
 }

 // Called when another command which requires one or more of the same
 // subsystems is scheduled to run
 protected void interrupted() {
	 Robot.horizontalGimbalTurning.resetLaser();
 }
}
